/* SQLite DB */
/* Initialization script */

CREATE TABLE IF NOT EXISTS users (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	login TEXT(20) NOT NULL,
	password TEXT(60) NOT NULL,
	UNIQUE(login)
);

CREATE TABLE IF NOT EXISTS games (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    board_size INTEGER NOT NULL,
	date_created INTEGER NOT NULL,
	player1 INTEGER NOT NULL,
	player2 INTEGER NOT NULL,
	closed INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT games_FK_p1 FOREIGN KEY (player1) REFERENCES users(id),
	CONSTRAINT games_FK_p2 FOREIGN KEY (player2) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS boards_map (
	game_id INTEGER NOT NULL,
	X INTEGER NOT NULL,
	Y INTEGER NOT NULL,
	player_id INTEGER NOT NULL,
	date INTEGER NOT NULL,
	CONSTRAINT board_FK FOREIGN KEY (game_id) REFERENCES games(id)
);
